Django-Porfolio/blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [path('', render_posts, name='posts'),
               path('posts/<int:post_id>', post_detail, name='post_detail')]

Django-Porfolio/django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-Porfolio/blog/models.py
from django.db import models
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

Django-Porfolio/portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True) 

Django-Porfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from . models import Post


def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})

Django-Porfolio/portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html',{'projects':projects})
# Create your views here.

Django-Porfolio/blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}
<div class="text-center">
<h2>{{post.title}}</h2>
<h3 class="my-2 h5 text-muted">{{post.date|date:'F jS, Y'}}</h3>
<img src="{{post.image.url}}" alt="" class="img-fluid">
<div class="my-4">
    <p>{{post.description|safe}}</p>
</div>
</div>
{% endblock %}

Django-Porfolio/blog/templates/posts.html
{% extends 'layout.html' %} {% block content %}
<h1>Posts</h1>
{% for post in posts%}

<div class="p-3">
    <div class="card card-body">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="" class="img-fluid">
            </div>
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description|striptags|truncatechars:100}}</p>
                <h2>{{post.date|date:'M d Y'|upper}}</h2>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>


{% endfor %}
{% endblock %}

Django-Porfolio/portfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}

<header class="row">
    <div class="col-md-4">
        <img src="{% static 'portfolio/Juli.jpg' %}" alt="" class="img-fluid">
    </div>

    <div class="col-md-8 my-auto">
        <h1>I am <strong>Julian Rios</strong></h1>
        <h3>I am Product Manager, and Python/Ruby/Javascript Backend Developer</h3>
        <p>{% lorem 1 %}</p>
        <a href="{% static 'portfolio/Desigualdad.pdf' %}" class="btn btn-primary btn-g rounded-0 my-3" target="-black">Download CV</a>
    </div>
</header>

<div class="row my-4 text-center">
    <h3>My Projects</h3>
    <p>{% lorem 1 %}</p>

{% for project in projects%}

<div class="col-md-4 p-4">
    <div class="card card-project">
        <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top">
        <div class="card-body">

        <h2>{{project.title}}</h2> <p>{{project.description}}</p>
        

        {% if project.url%}
        <a href="{{project.url}}" target="_blank">{{project.url}}</a>
        
        {%endif%}
        </div>
    </div>
</div>

</div>


{% endfor %}
{% endblock %}

Django-Porfolio/portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}"

<body>

    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock%}
    </div>

</body>

</html>

Django-Porfolio/portfolio/templates/partials/navbar.html
{% load static %}
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
        <a class="nav-link active fw-bold fst-italic" aria-current="page" href="/">JR</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:posts'%}">Blog</a>
    </li>
    <li class="nav-item">
        <a class="btn btn-primary btn-sm d-flex align-items-center" href="{% static 'portfolio/Desigualdad.pdf' %}" target="_blank">Download CV</a>
    </li>
</ul>